name: Spotify weekly adder Action

on:
    schedule:
        #Runs every wednesday at 12am
        - cron: '0 0 * * 3'

jobs:
    build:
        runs-on: ubuntu-latest #The machine that will run the workflow

        steps:
        - name: setup python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10' #Uses python 3.10 for this workflow
        #This sets up python on our machine

        - name: install python packages #This will install all of our dependancies
          run: | 
            python -m pip install --upgrade pip
            python -m pip install requests
        #This will upgrade our pip and install our only dependancy which is the requests library

        - name: checkout github repo
          uses: actions/checkout@v1 #This checks out the github repo that is being used

        - name: Run weekly_adder.py
          env: 
              CLIENT_ID: ${{ secrets.CLIENT_ID }}
              CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
              PLAYLIST_NAME: ${{ secrets.PLAYLIST }}
              TOKEN: ${{ secrets.TOKEN }}
          run: |
            python weekly_adder.py --client-id CLIENT_ID --client-secret CLIENT_SECRET --playlist-name PLAYLIST_NAME --token TOKEN
