name: Spotify weekly adder Action

on:
    schedule:
        #Runs every Tuesday at 1am
        - cron: '0 1 * * 2'

jobs:
    build:
        runs-on: ubuntu-latest #The machine that will run the workflow

        steps:
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9' #Uses python 3.10 for this workflow
        #This sets up python on our machine

        - name: install python packages #This will install all of our dependancies
          run: | 
            python -m pip install --upgrade pip
            python -m pip install requests
        #This will upgrade our pip and install our only dependancy which is the requests library

        - name: Run weekly_adder.py
          env: 
              CLIENT_ID: ${{ secrets.CLIENT_ID }}
              CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
              PLAYLIST_NAME: ${{ secrets.PLAYLIST }}
              TOKEN: ${{ secrets.TOKEN }}
          run: |
            python weekly_adder.py
        #This sets up our environment and actually runs our script
